name: Build libFMS test with autotools

on: [push]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/fms/fms-ci-rocky-gnu:13.2.0
      env:
        TEST_VERBOSE: 1
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: build FMS
      run: |
           cd FMS
           autoreconf -iv
           ./configure --enable-portable-kinds --prefix=$PWD/gnuFMS
           make
           cd ../
    - name: build cFMS
      env:
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$PWD/FMS/gnuFMS/lib
        FFLAGS: $FFLAGS -I$PWD/FMS/gnuFMS/include
        CFLAGS: $CFLAGS -I$PWD/FMS/gnuFMS/include
        LDFLAGS: $LDFLAGS -lFMS -L/$PWD/FMS/gnuFMS/lib
      run: |
        autoreconf -iv
        ./configure --prefix=$PWD/cgnuFMS
        make check
                            
        
            

