name: Build libFMS test with autotools

on: [push, pull_request]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/fms/fms-ci-rocky-gnu:13.2.0
      env:
        TEST_VERBOSE: 1
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: build FMS
      run: echo $PWD
           cd FMS  && echo $PWD &&
           autoreconf -iv &&
           ./configure --enable-portable-kinds --prefix=$PWD/gnuFMS &&
           make install
           cd ../
    - name: build cFMS
      run:  autoreconf -iv &&
            ./configure FCFLAGS="$FCFLAGS -I/usr/include" CFLAGS="$CFLAGS -I/usr/include" LDFLAGS="$LDFLAGS -L$PWD/FMS/gnuFMS"
            make
    - name:
      run: make check
            

