name: Build libFMS test with autotools

on: [push]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/fms/fms-ci-rocky-gnu:13.2.0
      env:
        TEST_VERBOSE: 1
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: build FMS
      run: |
        cd FMS
        export FCFLAGS="$FCFLAGS -fPIC"
        export CFLAGS="$CFLAGS -fPIC"
        autoreconf -iv
        ./configure --enable-portable-kinds --prefix=$PWD/cFMS/gnuFMS
        make install
        cd ../
    - name: test
      run: $PWD/.github/workflows/test.sh
                            
        
            

